### ISSUE TITLE
Problems setting the cookie expiration time back to "session"

### ISSUE THREAD

**Issue by dolgafar** [mainmatter/ember-cli-simple-auth-cookie-store#5]
I'm doing a "remember me" function on my login. But when i set exp. time to null, it just keeps the old exp time. 

Reproduce like this:
1. Set exp time to 14 days
2. Login and get session
3. Invalidate session (logout)
4. Login again but this time set exp date to null
5. Get new session .. 
6. Exp time is still 14 days!!

I'v made a small fix, by just clearing the cookie before setting it, which solved the problem. But it might not be the desired behavior IMHO.

My auth code:

```
            if (this.get('isValid')) {
                // Set cookie time (remember me) - clearing cookie first to make sure exp. time is correctly set.
                this.get('session.store').clear(); // Fix to get correct session time
                this.get('session.store').cookieExpirationTime = this.get('rememberMe') ? (14 * 24 * 60 * 60) : null;
                var data = this.getProperties('identification', 'password');
                return this.get('session').authenticate('oauth-custom:oauth2-password-grant', data);
            }
```

**Comment by marcoow** [comment]
Changing the cookie expiration time when the cookie is already present doesn't really work. I'm also not sure it would actually be possible to support that due to problems with tab/window synchronization. 

Anyway I'd say the correct way to support expiring sessions when using token based with would be using expiring cookies anyway as the token would actually still be valid on the server side although the cookie has been deleted on the client. 

Given that I'm not sure this should be considered a bug.

**Comment by dolgafar** [comment]
No worries, I will just stick to deleting the cookie, when a new user logs in.

Expiring the cookie on server is a problem, because i have no sure way of known when session ends (e.g. browser closes). Instead the server deletes tokens more than 14 days old.

Close.. moving on :)
